# Generated by Django 5.2.1 on 2025-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('design', 'Design'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=80, help_text='Skill level (0-100)'),
        ),
    ]
