# Generated by Django 5.2.1 on 2025-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskills', '0002_skill_category_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps & Deployment'), ('design', 'Design'), ('other', 'Tools & Other')], default='other', max_length=20),
        ),
    ]
