# Generated by Django 5.2.1 on 2025-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('design', 'Design'), ('mobile', 'Mobile App'), ('ml', 'Machine Learning'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('preview_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('project_date', models.DateField()),
                ('skills_used', models.CharField(max_length=255)),
            ],
        ),
    ]
