# Generated by Django 5.2.1 on 2025-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
        ('myskills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal Project'), ('client', 'Client Work'), ('hackathon', 'Hackathon'), ('group', 'Group Project')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_used',
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(blank=True, to='myskills.skill'),
        ),
    ]
