# Generated by Django 5.2.1 on 2025-05-22 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('institution', models.TextField(blank=True, null=True)),
                ('degree', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Location', max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('experience_year', models.IntegerField(default=0, help_text='Years of experience in the field')),
                ('achievements', models.TextField(blank=True, null=True)),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
