# Generated by Django 5.2.1 on 2025-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
