# Generated by Django 5.2.1 on 2025-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x',
            field=models.URLField(blank=True),
        ),
    ]
